title = "herstell.org"
baseURL = "https://herstell.org"
theme = "researcher"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]
enableEmoji = true
math = false  # enable KaTeX (https://katex.org/) globally

[params]
  author = "Danny Herstell"
  description = "A simple blog for myself"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "By Danny Herstell"
    url = "https://github.com/dannyherstell"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    weight = 2
  [[menu.main]]
    name = "Diet"
    url = "Stoffwechseldiaet.pdf"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files